org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=NadienDev
group=nadiendev.ultimateponderadditions
modid=ultimateponderadditions
mod_name=UltimatePonderAdditions
mod_named=Ultimate Ponder Additions
description=Ultimate Ponder Additions is a content addon for Ponder that adds interactive documentation for other mods.
license=MIT
mod_version=1.4.0
tag_lanzador=NeoForge

mcversion=1.21.1
neoversion=21.1.240
loader_version=[4,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

ponder_version=1.0.69
flywheel_version=1.0.6-44
guideme_version=21.1.17

jei_version=19.27.0.340

runtime_integrated_mods=true
industrialforegoing_version=1.21-3.6.39
titanium_version=1.21-4.0.45
functionalstorage_version=1.21-1.5.7
modernchickens_version=2.5.0
ae2_version=19.2.17

exdeorum_version=3.12
botanypots_version=21.1.44
bookshelf_version=21.1.81
prickle_version=21.1.11
pylons_version=5.4.2
mekanism_version=1.21.1-10.7.19.85
arsnouveau_version=5.13.0
geckolib_version=4.9.2
curios_version=9.5.1+1.21.1
modernfoundry_version=4.1.6
hilt_version=1.14
